# Generated by Django 5.0.4 on 2024-04-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="description",
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name="produit",
            name="image2",
            field=models.ImageField(blank=True, default=False, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="produit",
            name="image3",
            field=models.ImageField(blank=True, default=False, null=True, upload_to=""),
        ),
    ]
