# Generated by Django 5.0.4 on 2024-04-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_produit_description_produit_image2_produit_image3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="produit",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
