# Generated by Django 5.0.4 on 2024-04-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_alter_produit_image2_alter_produit_image3"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
