# Generated by Django 5.0.4 on 2024-05-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_produit_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="addresschipping",
            name="cash",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
