# Generated by Django 5.0.4 on 2024-05-05 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_addresschipping_cash_category_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("digital", models.BooleanField(blank=True, default=False, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("image2", models.ImageField(blank=True, null=True, upload_to="")),
                ("image3", models.ImageField(blank=True, null=True, upload_to="")),
                ("date_ajout", models.DateTimeField(default=django.utils.timezone.now)),
                ("description", models.TextField(default=False)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-date_ajout"],
            },
        ),
    ]
