# Generated by Django 5.0.4 on 2024-05-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_plats"),
    ]

    operations = [
        migrations.AddField(
            model_name="plats",
            name="programme",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
