# Generated by Django 5.0.4 on 2024-05-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_plats_programme"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammePlats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.RemoveField(
            model_name="plats",
            name="programme",
        ),
    ]
