# Generated by Django 5.0.4 on 2024-05-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_programmeplats_remove_plats_programme"),
    ]

    operations = [
        migrations.AddField(
            model_name="plats",
            name="livraison",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="produit",
            name="livraison",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
