# Generated by Django 5.0.4 on 2025-09-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_plats_livraison_produit_livraison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='plats',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='plats',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plats/'),
        ),
        migrations.AlterField(
            model_name='plats',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='plats/'),
        ),
        migrations.AlterField(
            model_name='plats',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='plats/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
        migrations.AlterField(
            model_name='programmeplats',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programme/'),
        ),
    ]
