# Generated by Django 5.0.4 on 2025-09-27 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_category_image_alter_plats_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.produit')),
            ],
            options={
                'ordering': ['-date_ajout'],
                'unique_together': {('client', 'produit')},
            },
        ),
    ]
