# Generated by Django 5.0.4 on 2025-09-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_favoris'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commandearticle',
            unique_together={('commande', 'produit')},
        ),
    ]
